export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED"

export const INCREASE_THE_NUMBER_OF_PRODUCT = "INCREASE_THE_NUMBER_OF_PRODUCT"
export const REDUCE_THE_NUMBER_OF_PRODUCT = "REDUCE_THE_NUMBER_OF_PRODUCT"

export const ADD_ITEM_PRODUCT_TO_CART = "ADD_ITEM_PRODUCT_TO_CART"

export const GET_DATA_FROM_CART = "GET_DATA_FROM_CART"
export const GET_DATA_FROM_CART_SUCCESS = "GET_DATA_FROM_CART_SUCCESS"

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const SAGA_TO_REDUCER_REMOVE_ITEM_FROM_CART = "SAGA_TO_REDUCER_REMOVE_ITEM_FROM_CART"

